### ISSUE TITLE
 TypeError: Cannot create property 'context' on string 'error downloading file https://www.youtube.com/watch?v=J5QtPL4F3A4'

### ISSUE THREAD

**Issue by hevisko** [pnhoang/dl-youtube-videos#3]
```
root@YouTubePuller:/puller/pp/dl-youtube-videos-linux-amd64# ./bin/dl-youtube-videos test.csv
Download Youtube Videos listed in this CSV file: test.csv
(node:36737) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'context' on string 'error downloading file https://www.youtube.com/watch?v=J5QtPL4F3A4'
    at tasks.then.catch.error (/puller/pp/dl-youtube-videos-linux-amd64/node_modules/listr/index.js:112:19)
(node:36737) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36737) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ✖ Learn German online / Tina visits me. / Vocabulary apartment / lesson 15
    Deutsch lernen mit Dialogen / Lektion 39 / Imperativ / Komparativ und Superlativ
```

**Comment by hhankj2u** [comment]
Make sure to install Python in your system

**Comment by raftudela** [comment]
I also received: 

```
> C:\Users\rafae\Downloads\dl-youtube-videos> bin\dl-youtube-videos C:\Users\rafae\Downloads\germtest.csv
> Download Youtube Videos listed in this CSV file: C:\Users\rafae\Downloads\germtest.csv
> (node:16296) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'context' on string 'error downloading file https://www.youtube.com/watch?v=J5QtPL4F3A4'
>     at tasks.then.catch.error (C:\Users\rafae\Downloads\dl-youtube-videos\node_modules\listr\index.js:112:19)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:16296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:16296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>   × Learn German online / Tina visits me. / Vocabulary apartment / lesson 15
>     Deutsch lernen mit Dialogen / Lektion 39 / Imperativ / Komparativ und Superlativ
```
I have python 3.11.2

How can I make it work?
Thanks

**Comment by pnhoang** [comment]
hey sorry, I am busy so far. I'll take a look at the issues soon and probably will update the script to a better version.

**Comment by Giddy-Up224** [comment]
@pnhoang 

I get the following error:

```
MyComputer@MyComputer-Latitude-7350:~/Downloads/dl-youtube-videos/bin$ dl-youtube-videos MangoJelly_Solutions.csv
node:internal/fs/utils:351
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/dl-youtube-videos/node_modules/youtube-dl/bin/details'
    at Object.openSync (node:fs:596:3)
    at readFileSync (node:fs:464:35)
    at module.exports (/usr/local/lib/node_modules/dl-youtube-videos/node_modules/youtube-dl/lib/get-binary.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/dl-youtube-videos/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/local/lib/node_modules/dl-youtube-videos/node_modules/youtube-dl/bin/details'
}

Node.js v18.19.1
```


I've checked and neither the 'bin' nor the `lib` folder exist. No wonder it can't find it!
`/usr/local/lib/node_modules/dl-youtube-videos/node_modules/youtube-dl` is all the further it can get.

I don't know what the contents of those files were so I can't move on.

Would've been super cool if this would've worked.

I can't create an issue so just commenting here...
